package com.example.genator.model;

import java.io.Serializable;

public class AlipayConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.app_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.charset
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String charset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.format
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String format;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.gateway_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String gatewayUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.notify_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String notifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.return_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String returnUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.sign_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String signType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.sys_service_provider_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String sysServiceProviderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.private_key
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String privateKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_config.public_key
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String publicKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.id
     *
     * @return the value of alipay_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.id
     *
     * @param id the value for alipay_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.app_id
     *
     * @return the value of alipay_config.app_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.app_id
     *
     * @param appId the value for alipay_config.app_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.charset
     *
     * @return the value of alipay_config.charset
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getCharset() {
        return charset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.charset
     *
     * @param charset the value for alipay_config.charset
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCharset(String charset) {
        this.charset = charset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.format
     *
     * @return the value of alipay_config.format
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.format
     *
     * @param format the value for alipay_config.format
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setFormat(String format) {
        this.format = format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.gateway_url
     *
     * @return the value of alipay_config.gateway_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getGatewayUrl() {
        return gatewayUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.gateway_url
     *
     * @param gatewayUrl the value for alipay_config.gateway_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setGatewayUrl(String gatewayUrl) {
        this.gatewayUrl = gatewayUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.notify_url
     *
     * @return the value of alipay_config.notify_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.notify_url
     *
     * @param notifyUrl the value for alipay_config.notify_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.return_url
     *
     * @return the value of alipay_config.return_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.return_url
     *
     * @param returnUrl the value for alipay_config.return_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.sign_type
     *
     * @return the value of alipay_config.sign_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.sign_type
     *
     * @param signType the value for alipay_config.sign_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setSignType(String signType) {
        this.signType = signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.sys_service_provider_id
     *
     * @return the value of alipay_config.sys_service_provider_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getSysServiceProviderId() {
        return sysServiceProviderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.sys_service_provider_id
     *
     * @param sysServiceProviderId the value for alipay_config.sys_service_provider_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setSysServiceProviderId(String sysServiceProviderId) {
        this.sysServiceProviderId = sysServiceProviderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.private_key
     *
     * @return the value of alipay_config.private_key
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.private_key
     *
     * @param privateKey the value for alipay_config.private_key
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_config.public_key
     *
     * @return the value of alipay_config.public_key
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getPublicKey() {
        return publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_config.public_key
     *
     * @param publicKey the value for alipay_config.public_key
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", charset=").append(charset);
        sb.append(", format=").append(format);
        sb.append(", gatewayUrl=").append(gatewayUrl);
        sb.append(", notifyUrl=").append(notifyUrl);
        sb.append(", returnUrl=").append(returnUrl);
        sb.append(", signType=").append(signType);
        sb.append(", sysServiceProviderId=").append(sysServiceProviderId);
        sb.append(", privateKey=").append(privateKey);
        sb.append(", publicKey=").append(publicKey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}