package com.example.genator.model;

import java.io.Serializable;

public class ColumnConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.table_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.column_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.column_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String columnType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.dict_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.extra
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String extra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.form_show
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Boolean formShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.form_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String formType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.key_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String keyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.list_show
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Boolean listShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.not_null
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Boolean notNull;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.query_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String queryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.remark
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column column_config.date_annotation
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String dateAnnotation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.id
     *
     * @return the value of column_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.id
     *
     * @param id the value for column_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.table_name
     *
     * @return the value of column_config.table_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.table_name
     *
     * @param tableName the value for column_config.table_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.column_name
     *
     * @return the value of column_config.column_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.column_name
     *
     * @param columnName the value for column_config.column_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.column_type
     *
     * @return the value of column_config.column_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.column_type
     *
     * @param columnType the value for column_config.column_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setColumnType(String columnType) {
        this.columnType = columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.dict_name
     *
     * @return the value of column_config.dict_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.dict_name
     *
     * @param dictName the value for column_config.dict_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setDictName(String dictName) {
        this.dictName = dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.extra
     *
     * @return the value of column_config.extra
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.extra
     *
     * @param extra the value for column_config.extra
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setExtra(String extra) {
        this.extra = extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.form_show
     *
     * @return the value of column_config.form_show
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Boolean getFormShow() {
        return formShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.form_show
     *
     * @param formShow the value for column_config.form_show
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setFormShow(Boolean formShow) {
        this.formShow = formShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.form_type
     *
     * @return the value of column_config.form_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getFormType() {
        return formType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.form_type
     *
     * @param formType the value for column_config.form_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setFormType(String formType) {
        this.formType = formType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.key_type
     *
     * @return the value of column_config.key_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getKeyType() {
        return keyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.key_type
     *
     * @param keyType the value for column_config.key_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setKeyType(String keyType) {
        this.keyType = keyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.list_show
     *
     * @return the value of column_config.list_show
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Boolean getListShow() {
        return listShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.list_show
     *
     * @param listShow the value for column_config.list_show
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setListShow(Boolean listShow) {
        this.listShow = listShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.not_null
     *
     * @return the value of column_config.not_null
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Boolean getNotNull() {
        return notNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.not_null
     *
     * @param notNull the value for column_config.not_null
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setNotNull(Boolean notNull) {
        this.notNull = notNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.query_type
     *
     * @return the value of column_config.query_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getQueryType() {
        return queryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.query_type
     *
     * @param queryType the value for column_config.query_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setQueryType(String queryType) {
        this.queryType = queryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.remark
     *
     * @return the value of column_config.remark
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.remark
     *
     * @param remark the value for column_config.remark
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column column_config.date_annotation
     *
     * @return the value of column_config.date_annotation
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getDateAnnotation() {
        return dateAnnotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column column_config.date_annotation
     *
     * @param dateAnnotation the value for column_config.date_annotation
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setDateAnnotation(String dateAnnotation) {
        this.dateAnnotation = dateAnnotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tableName=").append(tableName);
        sb.append(", columnName=").append(columnName);
        sb.append(", columnType=").append(columnType);
        sb.append(", dictName=").append(dictName);
        sb.append(", extra=").append(extra);
        sb.append(", formShow=").append(formShow);
        sb.append(", formType=").append(formType);
        sb.append(", keyType=").append(keyType);
        sb.append(", listShow=").append(listShow);
        sb.append(", notNull=").append(notNull);
        sb.append(", queryType=").append(queryType);
        sb.append(", remark=").append(remark);
        sb.append(", dateAnnotation=").append(dateAnnotation);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}