package com.example.genator.model;

import java.io.Serializable;
import java.util.Date;

public class DictDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_detail.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_detail.label
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_detail.value
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_detail.sort
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_detail.dict_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long dictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_detail.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_detail.id
     *
     * @return the value of dict_detail.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_detail.id
     *
     * @param id the value for dict_detail.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_detail.label
     *
     * @return the value of dict_detail.label
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_detail.label
     *
     * @param label the value for dict_detail.label
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_detail.value
     *
     * @return the value of dict_detail.value
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_detail.value
     *
     * @param value the value for dict_detail.value
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_detail.sort
     *
     * @return the value of dict_detail.sort
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_detail.sort
     *
     * @param sort the value for dict_detail.sort
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_detail.dict_id
     *
     * @return the value of dict_detail.dict_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_detail.dict_id
     *
     * @param dictId the value for dict_detail.dict_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setDictId(Long dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_detail.create_time
     *
     * @return the value of dict_detail.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_detail.create_time
     *
     * @param createTime the value for dict_detail.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", label=").append(label);
        sb.append(", value=").append(value);
        sb.append(", sort=").append(sort);
        sb.append(", dictId=").append(dictId);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}