package com.example.genator.model;

import java.io.Serializable;

public class GenConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_config.table_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_config.author
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_config.cover
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Boolean cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_config.module_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String moduleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_config.pack
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String pack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_config.path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_config.api_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String apiPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_config.prefix
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String prefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gen_config.api_alias
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String apiAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_config.id
     *
     * @return the value of gen_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_config.id
     *
     * @param id the value for gen_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_config.table_name
     *
     * @return the value of gen_config.table_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_config.table_name
     *
     * @param tableName the value for gen_config.table_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_config.author
     *
     * @return the value of gen_config.author
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_config.author
     *
     * @param author the value for gen_config.author
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_config.cover
     *
     * @return the value of gen_config.cover
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Boolean getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_config.cover
     *
     * @param cover the value for gen_config.cover
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCover(Boolean cover) {
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_config.module_name
     *
     * @return the value of gen_config.module_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_config.module_name
     *
     * @param moduleName the value for gen_config.module_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_config.pack
     *
     * @return the value of gen_config.pack
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getPack() {
        return pack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_config.pack
     *
     * @param pack the value for gen_config.pack
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setPack(String pack) {
        this.pack = pack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_config.path
     *
     * @return the value of gen_config.path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_config.path
     *
     * @param path the value for gen_config.path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_config.api_path
     *
     * @return the value of gen_config.api_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getApiPath() {
        return apiPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_config.api_path
     *
     * @param apiPath the value for gen_config.api_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setApiPath(String apiPath) {
        this.apiPath = apiPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_config.prefix
     *
     * @return the value of gen_config.prefix
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_config.prefix
     *
     * @param prefix the value for gen_config.prefix
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gen_config.api_alias
     *
     * @return the value of gen_config.api_alias
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getApiAlias() {
        return apiAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gen_config.api_alias
     *
     * @param apiAlias the value for gen_config.api_alias
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setApiAlias(String apiAlias) {
        this.apiAlias = apiAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tableName=").append(tableName);
        sb.append(", author=").append(author);
        sb.append(", cover=").append(cover);
        sb.append(", moduleName=").append(moduleName);
        sb.append(", pack=").append(pack);
        sb.append(", path=").append(path);
        sb.append(", apiPath=").append(apiPath);
        sb.append(", prefix=").append(prefix);
        sb.append(", apiAlias=").append(apiAlias);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}