package com.example.genator.model;

import java.io.Serializable;
import java.util.Date;

public class LocalStorage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_storage.id
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_storage.real_name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_storage.name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_storage.suffix
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_storage.path
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_storage.type
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_storage.size
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_storage.operate
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String operate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local_storage.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table local_storage
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_storage.id
     *
     * @return the value of local_storage.id
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_storage.id
     *
     * @param id the value for local_storage.id
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_storage.real_name
     *
     * @return the value of local_storage.real_name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_storage.real_name
     *
     * @param realName the value for local_storage.real_name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_storage.name
     *
     * @return the value of local_storage.name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_storage.name
     *
     * @param name the value for local_storage.name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_storage.suffix
     *
     * @return the value of local_storage.suffix
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_storage.suffix
     *
     * @param suffix the value for local_storage.suffix
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_storage.path
     *
     * @return the value of local_storage.path
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_storage.path
     *
     * @param path the value for local_storage.path
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_storage.type
     *
     * @return the value of local_storage.type
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_storage.type
     *
     * @param type the value for local_storage.type
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_storage.size
     *
     * @return the value of local_storage.size
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_storage.size
     *
     * @param size the value for local_storage.size
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_storage.operate
     *
     * @return the value of local_storage.operate
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getOperate() {
        return operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_storage.operate
     *
     * @param operate the value for local_storage.operate
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setOperate(String operate) {
        this.operate = operate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local_storage.create_time
     *
     * @return the value of local_storage.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local_storage.create_time
     *
     * @param createTime the value for local_storage.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local_storage
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", realName=").append(realName);
        sb.append(", name=").append(name);
        sb.append(", suffix=").append(suffix);
        sb.append(", path=").append(path);
        sb.append(", type=").append(type);
        sb.append(", size=").append(size);
        sb.append(", operate=").append(operate);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}