package com.example.genator.model;

import java.io.Serializable;
import java.util.Date;

public class Log implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.description
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.method
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.request_ip
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String requestIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.username
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.address
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.browser
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.exception_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String exceptionDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.params
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.create_time
     *
     * @return the value of log.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.create_time
     *
     * @param createTime the value for log.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.description
     *
     * @return the value of log.description
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.description
     *
     * @param description the value for log.description
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_type
     *
     * @return the value of log.log_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_type
     *
     * @param logType the value for log.log_type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setLogType(String logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.method
     *
     * @return the value of log.method
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.method
     *
     * @param method the value for log.method
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.request_ip
     *
     * @return the value of log.request_ip
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getRequestIp() {
        return requestIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.request_ip
     *
     * @param requestIp the value for log.request_ip
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.time
     *
     * @return the value of log.time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.time
     *
     * @param time the value for log.time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.username
     *
     * @return the value of log.username
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.username
     *
     * @param username the value for log.username
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.address
     *
     * @return the value of log.address
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.address
     *
     * @param address the value for log.address
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.browser
     *
     * @return the value of log.browser
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.browser
     *
     * @param browser the value for log.browser
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setBrowser(String browser) {
        this.browser = browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.exception_detail
     *
     * @return the value of log.exception_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getExceptionDetail() {
        return exceptionDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.exception_detail
     *
     * @param exceptionDetail the value for log.exception_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setExceptionDetail(String exceptionDetail) {
        this.exceptionDetail = exceptionDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.params
     *
     * @return the value of log.params
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.params
     *
     * @param params the value for log.params
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setParams(String params) {
        this.params = params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createTime=").append(createTime);
        sb.append(", description=").append(description);
        sb.append(", logType=").append(logType);
        sb.append(", method=").append(method);
        sb.append(", requestIp=").append(requestIp);
        sb.append(", time=").append(time);
        sb.append(", username=").append(username);
        sb.append(", address=").append(address);
        sb.append(", browser=").append(browser);
        sb.append(", exceptionDetail=").append(exceptionDetail);
        sb.append(", params=").append(params);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}