package com.example.genator.model;

import java.io.Serializable;
import java.util.Date;

public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.i_frame
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private Boolean iFrame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.component
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.pid
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.sort
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private Long sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.path
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.cache
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private Boolean cache;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.hidden
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private Boolean hidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.component_name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String componentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.permission
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.type
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.i_frame
     *
     * @return the value of menu.i_frame
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public Boolean getiFrame() {
        return iFrame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.i_frame
     *
     * @param iFrame the value for menu.i_frame
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setiFrame(Boolean iFrame) {
        this.iFrame = iFrame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.component
     *
     * @return the value of menu.component
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.component
     *
     * @param component the value for menu.component
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setComponent(String component) {
        this.component = component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.pid
     *
     * @return the value of menu.pid
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.pid
     *
     * @param pid the value for menu.pid
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.sort
     *
     * @return the value of menu.sort
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.sort
     *
     * @param sort the value for menu.sort
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.icon
     *
     * @return the value of menu.icon
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.icon
     *
     * @param icon the value for menu.icon
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.path
     *
     * @return the value of menu.path
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.path
     *
     * @param path the value for menu.path
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.cache
     *
     * @return the value of menu.cache
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public Boolean getCache() {
        return cache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.cache
     *
     * @param cache the value for menu.cache
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setCache(Boolean cache) {
        this.cache = cache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.hidden
     *
     * @return the value of menu.hidden
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public Boolean getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.hidden
     *
     * @param hidden the value for menu.hidden
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setHidden(Boolean hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.component_name
     *
     * @return the value of menu.component_name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getComponentName() {
        return componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.component_name
     *
     * @param componentName the value for menu.component_name
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setComponentName(String componentName) {
        this.componentName = componentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.create_time
     *
     * @return the value of menu.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.create_time
     *
     * @param createTime the value for menu.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.permission
     *
     * @return the value of menu.permission
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.permission
     *
     * @param permission the value for menu.permission
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.type
     *
     * @return the value of menu.type
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.type
     *
     * @param type the value for menu.type
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", iFrame=").append(iFrame);
        sb.append(", name=").append(name);
        sb.append(", component=").append(component);
        sb.append(", pid=").append(pid);
        sb.append(", sort=").append(sort);
        sb.append(", icon=").append(icon);
        sb.append(", path=").append(path);
        sb.append(", cache=").append(cache);
        sb.append(", hidden=").append(hidden);
        sb.append(", componentName=").append(componentName);
        sb.append(", createTime=").append(createTime);
        sb.append(", permission=").append(permission);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}