package com.example.genator.model;

import java.io.Serializable;
import java.util.Date;

public class MntApp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_app.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_app.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_app.upload_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String uploadPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_app.deploy_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String deployPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_app.backup_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String backupPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_app.port
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_app.start_script
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String startScript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_app.deploy_script
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String deployScript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_app.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mnt_app
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_app.id
     *
     * @return the value of mnt_app.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_app.id
     *
     * @param id the value for mnt_app.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_app.name
     *
     * @return the value of mnt_app.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_app.name
     *
     * @param name the value for mnt_app.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_app.upload_path
     *
     * @return the value of mnt_app.upload_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getUploadPath() {
        return uploadPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_app.upload_path
     *
     * @param uploadPath the value for mnt_app.upload_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setUploadPath(String uploadPath) {
        this.uploadPath = uploadPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_app.deploy_path
     *
     * @return the value of mnt_app.deploy_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getDeployPath() {
        return deployPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_app.deploy_path
     *
     * @param deployPath the value for mnt_app.deploy_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setDeployPath(String deployPath) {
        this.deployPath = deployPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_app.backup_path
     *
     * @return the value of mnt_app.backup_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getBackupPath() {
        return backupPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_app.backup_path
     *
     * @param backupPath the value for mnt_app.backup_path
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setBackupPath(String backupPath) {
        this.backupPath = backupPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_app.port
     *
     * @return the value of mnt_app.port
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_app.port
     *
     * @param port the value for mnt_app.port
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_app.start_script
     *
     * @return the value of mnt_app.start_script
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getStartScript() {
        return startScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_app.start_script
     *
     * @param startScript the value for mnt_app.start_script
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setStartScript(String startScript) {
        this.startScript = startScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_app.deploy_script
     *
     * @return the value of mnt_app.deploy_script
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getDeployScript() {
        return deployScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_app.deploy_script
     *
     * @param deployScript the value for mnt_app.deploy_script
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setDeployScript(String deployScript) {
        this.deployScript = deployScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_app.create_time
     *
     * @return the value of mnt_app.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_app.create_time
     *
     * @param createTime the value for mnt_app.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_app
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", uploadPath=").append(uploadPath);
        sb.append(", deployPath=").append(deployPath);
        sb.append(", backupPath=").append(backupPath);
        sb.append(", port=").append(port);
        sb.append(", startScript=").append(startScript);
        sb.append(", deployScript=").append(deployScript);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}