package com.example.genator.model;

import java.io.Serializable;

public class MntDeployServer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_deploy_server.deploy_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long deployId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_deploy_server.server_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mnt_deploy_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_deploy_server.deploy_id
     *
     * @return the value of mnt_deploy_server.deploy_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getDeployId() {
        return deployId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_deploy_server.deploy_id
     *
     * @param deployId the value for mnt_deploy_server.deploy_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setDeployId(Long deployId) {
        this.deployId = deployId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_deploy_server.server_id
     *
     * @return the value of mnt_deploy_server.server_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_deploy_server.server_id
     *
     * @param serverId the value for mnt_deploy_server.server_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setServerId(Long serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deployId=").append(deployId);
        sb.append(", serverId=").append(serverId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}