package com.example.genator.model;

import java.io.Serializable;
import java.util.Date;

public class MntDatabase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_database.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_database.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_database.jdbc_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String jdbcUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_database.user_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_database.pwd
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnt_database.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_database.id
     *
     * @return the value of mnt_database.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_database.id
     *
     * @param id the value for mnt_database.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_database.name
     *
     * @return the value of mnt_database.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_database.name
     *
     * @param name the value for mnt_database.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_database.jdbc_url
     *
     * @return the value of mnt_database.jdbc_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getJdbcUrl() {
        return jdbcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_database.jdbc_url
     *
     * @param jdbcUrl the value for mnt_database.jdbc_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setJdbcUrl(String jdbcUrl) {
        this.jdbcUrl = jdbcUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_database.user_name
     *
     * @return the value of mnt_database.user_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_database.user_name
     *
     * @param userName the value for mnt_database.user_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_database.pwd
     *
     * @return the value of mnt_database.pwd
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_database.pwd
     *
     * @param pwd the value for mnt_database.pwd
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnt_database.create_time
     *
     * @return the value of mnt_database.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnt_database.create_time
     *
     * @param createTime the value for mnt_database.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", jdbcUrl=").append(jdbcUrl);
        sb.append(", userName=").append(userName);
        sb.append(", pwd=").append(pwd);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}