package com.example.genator.model;

import java.io.Serializable;

public class MonitorServer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.cpu_core
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Integer cpuCore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.cpu_rate
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Double cpuRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.disk_total
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Double diskTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.disk_used
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Double diskUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.mem_total
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Double memTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.mem_used
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Double memUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.port
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.sort
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.state
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.swap_total
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Double swapTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.swap_used
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Double swapUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor_server.address
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitor_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.id
     *
     * @return the value of monitor_server.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.id
     *
     * @param id the value for monitor_server.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.cpu_core
     *
     * @return the value of monitor_server.cpu_core
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Integer getCpuCore() {
        return cpuCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.cpu_core
     *
     * @param cpuCore the value for monitor_server.cpu_core
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCpuCore(Integer cpuCore) {
        this.cpuCore = cpuCore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.cpu_rate
     *
     * @return the value of monitor_server.cpu_rate
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Double getCpuRate() {
        return cpuRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.cpu_rate
     *
     * @param cpuRate the value for monitor_server.cpu_rate
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCpuRate(Double cpuRate) {
        this.cpuRate = cpuRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.disk_total
     *
     * @return the value of monitor_server.disk_total
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Double getDiskTotal() {
        return diskTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.disk_total
     *
     * @param diskTotal the value for monitor_server.disk_total
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setDiskTotal(Double diskTotal) {
        this.diskTotal = diskTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.disk_used
     *
     * @return the value of monitor_server.disk_used
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Double getDiskUsed() {
        return diskUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.disk_used
     *
     * @param diskUsed the value for monitor_server.disk_used
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setDiskUsed(Double diskUsed) {
        this.diskUsed = diskUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.mem_total
     *
     * @return the value of monitor_server.mem_total
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Double getMemTotal() {
        return memTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.mem_total
     *
     * @param memTotal the value for monitor_server.mem_total
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setMemTotal(Double memTotal) {
        this.memTotal = memTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.mem_used
     *
     * @return the value of monitor_server.mem_used
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Double getMemUsed() {
        return memUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.mem_used
     *
     * @param memUsed the value for monitor_server.mem_used
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setMemUsed(Double memUsed) {
        this.memUsed = memUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.name
     *
     * @return the value of monitor_server.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.name
     *
     * @param name the value for monitor_server.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.port
     *
     * @return the value of monitor_server.port
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.port
     *
     * @param port the value for monitor_server.port
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.sort
     *
     * @return the value of monitor_server.sort
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.sort
     *
     * @param sort the value for monitor_server.sort
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.state
     *
     * @return the value of monitor_server.state
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.state
     *
     * @param state the value for monitor_server.state
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.swap_total
     *
     * @return the value of monitor_server.swap_total
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Double getSwapTotal() {
        return swapTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.swap_total
     *
     * @param swapTotal the value for monitor_server.swap_total
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setSwapTotal(Double swapTotal) {
        this.swapTotal = swapTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.swap_used
     *
     * @return the value of monitor_server.swap_used
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Double getSwapUsed() {
        return swapUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.swap_used
     *
     * @param swapUsed the value for monitor_server.swap_used
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setSwapUsed(Double swapUsed) {
        this.swapUsed = swapUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor_server.address
     *
     * @return the value of monitor_server.address
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor_server.address
     *
     * @param address the value for monitor_server.address
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cpuCore=").append(cpuCore);
        sb.append(", cpuRate=").append(cpuRate);
        sb.append(", diskTotal=").append(diskTotal);
        sb.append(", diskUsed=").append(diskUsed);
        sb.append(", memTotal=").append(memTotal);
        sb.append(", memUsed=").append(memUsed);
        sb.append(", name=").append(name);
        sb.append(", port=").append(port);
        sb.append(", sort=").append(sort);
        sb.append(", state=").append(state);
        sb.append(", swapTotal=").append(swapTotal);
        sb.append(", swapUsed=").append(swapUsed);
        sb.append(", address=").append(address);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}