package com.example.genator.model;

import java.io.Serializable;
import java.util.Date;

public class Picture implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.delete_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String deleteUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.filename
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.height
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.size
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.username
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.width
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.md5code
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String md5code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table picture
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.id
     *
     * @return the value of picture.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.id
     *
     * @param id the value for picture.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.create_time
     *
     * @return the value of picture.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.create_time
     *
     * @param createTime the value for picture.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.delete_url
     *
     * @return the value of picture.delete_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getDeleteUrl() {
        return deleteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.delete_url
     *
     * @param deleteUrl the value for picture.delete_url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setDeleteUrl(String deleteUrl) {
        this.deleteUrl = deleteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.filename
     *
     * @return the value of picture.filename
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.filename
     *
     * @param filename the value for picture.filename
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.height
     *
     * @return the value of picture.height
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.height
     *
     * @param height the value for picture.height
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setHeight(String height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.size
     *
     * @return the value of picture.size
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.size
     *
     * @param size the value for picture.size
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.url
     *
     * @return the value of picture.url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.url
     *
     * @param url the value for picture.url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.username
     *
     * @return the value of picture.username
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.username
     *
     * @param username the value for picture.username
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.width
     *
     * @return the value of picture.width
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.width
     *
     * @param width the value for picture.width
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setWidth(String width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.md5code
     *
     * @return the value of picture.md5code
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getMd5code() {
        return md5code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.md5code
     *
     * @param md5code the value for picture.md5code
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setMd5code(String md5code) {
        this.md5code = md5code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createTime=").append(createTime);
        sb.append(", deleteUrl=").append(deleteUrl);
        sb.append(", filename=").append(filename);
        sb.append(", height=").append(height);
        sb.append(", size=").append(size);
        sb.append(", url=").append(url);
        sb.append(", username=").append(username);
        sb.append(", width=").append(width);
        sb.append(", md5code=").append(md5code);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}