package com.example.genator.model;

import java.io.Serializable;

public class QiniuConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_config.bucket
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String bucket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_config.host
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_config.type
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_config.zone
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String zone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_config.access_key
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String accessKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_config.secret_key
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private String secretKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_config.id
     *
     * @return the value of qiniu_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_config.id
     *
     * @param id the value for qiniu_config.id
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_config.bucket
     *
     * @return the value of qiniu_config.bucket
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getBucket() {
        return bucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_config.bucket
     *
     * @param bucket the value for qiniu_config.bucket
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setBucket(String bucket) {
        this.bucket = bucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_config.host
     *
     * @return the value of qiniu_config.host
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_config.host
     *
     * @param host the value for qiniu_config.host
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_config.type
     *
     * @return the value of qiniu_config.type
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_config.type
     *
     * @param type the value for qiniu_config.type
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_config.zone
     *
     * @return the value of qiniu_config.zone
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_config.zone
     *
     * @param zone the value for qiniu_config.zone
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setZone(String zone) {
        this.zone = zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_config.access_key
     *
     * @return the value of qiniu_config.access_key
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getAccessKey() {
        return accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_config.access_key
     *
     * @param accessKey the value for qiniu_config.access_key
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setAccessKey(String accessKey) {
        this.accessKey = accessKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_config.secret_key
     *
     * @return the value of qiniu_config.secret_key
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_config.secret_key
     *
     * @param secretKey the value for qiniu_config.secret_key
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bucket=").append(bucket);
        sb.append(", host=").append(host);
        sb.append(", type=").append(type);
        sb.append(", zone=").append(zone);
        sb.append(", accessKey=").append(accessKey);
        sb.append(", secretKey=").append(secretKey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}