package com.example.genator.model;

import java.io.Serializable;
import java.util.Date;

public class QiniuContent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_content.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_content.bucket
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String bucket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_content.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_content.size
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_content.type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_content.update_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_content.url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiniu_content.suffix
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_content.id
     *
     * @return the value of qiniu_content.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_content.id
     *
     * @param id the value for qiniu_content.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_content.bucket
     *
     * @return the value of qiniu_content.bucket
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getBucket() {
        return bucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_content.bucket
     *
     * @param bucket the value for qiniu_content.bucket
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setBucket(String bucket) {
        this.bucket = bucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_content.name
     *
     * @return the value of qiniu_content.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_content.name
     *
     * @param name the value for qiniu_content.name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_content.size
     *
     * @return the value of qiniu_content.size
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_content.size
     *
     * @param size the value for qiniu_content.size
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_content.type
     *
     * @return the value of qiniu_content.type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_content.type
     *
     * @param type the value for qiniu_content.type
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_content.update_time
     *
     * @return the value of qiniu_content.update_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_content.update_time
     *
     * @param updateTime the value for qiniu_content.update_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_content.url
     *
     * @return the value of qiniu_content.url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_content.url
     *
     * @param url the value for qiniu_content.url
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiniu_content.suffix
     *
     * @return the value of qiniu_content.suffix
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiniu_content.suffix
     *
     * @param suffix the value for qiniu_content.suffix
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bucket=").append(bucket);
        sb.append(", name=").append(name);
        sb.append(", size=").append(size);
        sb.append(", type=").append(type);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", url=").append(url);
        sb.append(", suffix=").append(suffix);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}