package com.example.genator.model;

import java.io.Serializable;
import java.util.Date;

public class QuartzLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_log.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_log.baen_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String baenName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_log.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_log.cron_expression
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String cronExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_log.is_success
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Boolean isSuccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_log.job_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_log.method_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_log.params
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_log.time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_log.exception_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String exceptionDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_log.id
     *
     * @return the value of quartz_log.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_log.id
     *
     * @param id the value for quartz_log.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_log.baen_name
     *
     * @return the value of quartz_log.baen_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getBaenName() {
        return baenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_log.baen_name
     *
     * @param baenName the value for quartz_log.baen_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setBaenName(String baenName) {
        this.baenName = baenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_log.create_time
     *
     * @return the value of quartz_log.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_log.create_time
     *
     * @param createTime the value for quartz_log.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_log.cron_expression
     *
     * @return the value of quartz_log.cron_expression
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_log.cron_expression
     *
     * @param cronExpression the value for quartz_log.cron_expression
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_log.is_success
     *
     * @return the value of quartz_log.is_success
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Boolean getIsSuccess() {
        return isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_log.is_success
     *
     * @param isSuccess the value for quartz_log.is_success
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setIsSuccess(Boolean isSuccess) {
        this.isSuccess = isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_log.job_name
     *
     * @return the value of quartz_log.job_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_log.job_name
     *
     * @param jobName the value for quartz_log.job_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_log.method_name
     *
     * @return the value of quartz_log.method_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_log.method_name
     *
     * @param methodName the value for quartz_log.method_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_log.params
     *
     * @return the value of quartz_log.params
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_log.params
     *
     * @param params the value for quartz_log.params
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setParams(String params) {
        this.params = params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_log.time
     *
     * @return the value of quartz_log.time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_log.time
     *
     * @param time the value for quartz_log.time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_log.exception_detail
     *
     * @return the value of quartz_log.exception_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getExceptionDetail() {
        return exceptionDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_log.exception_detail
     *
     * @param exceptionDetail the value for quartz_log.exception_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setExceptionDetail(String exceptionDetail) {
        this.exceptionDetail = exceptionDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", baenName=").append(baenName);
        sb.append(", createTime=").append(createTime);
        sb.append(", cronExpression=").append(cronExpression);
        sb.append(", isSuccess=").append(isSuccess);
        sb.append(", jobName=").append(jobName);
        sb.append(", methodName=").append(methodName);
        sb.append(", params=").append(params);
        sb.append(", time=").append(time);
        sb.append(", exceptionDetail=").append(exceptionDetail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}