package com.example.genator.model;

import java.io.Serializable;
import java.util.Date;

public class QuartzJob implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.bean_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String beanName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.cron_expression
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String cronExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.is_pause
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Boolean isPause;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.job_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.method_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.params
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.remark
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quartz_job.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quartz_job
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.id
     *
     * @return the value of quartz_job.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.id
     *
     * @param id the value for quartz_job.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.bean_name
     *
     * @return the value of quartz_job.bean_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getBeanName() {
        return beanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.bean_name
     *
     * @param beanName the value for quartz_job.bean_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setBeanName(String beanName) {
        this.beanName = beanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.cron_expression
     *
     * @return the value of quartz_job.cron_expression
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.cron_expression
     *
     * @param cronExpression the value for quartz_job.cron_expression
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.is_pause
     *
     * @return the value of quartz_job.is_pause
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Boolean getIsPause() {
        return isPause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.is_pause
     *
     * @param isPause the value for quartz_job.is_pause
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setIsPause(Boolean isPause) {
        this.isPause = isPause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.job_name
     *
     * @return the value of quartz_job.job_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.job_name
     *
     * @param jobName the value for quartz_job.job_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.method_name
     *
     * @return the value of quartz_job.method_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.method_name
     *
     * @param methodName the value for quartz_job.method_name
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.params
     *
     * @return the value of quartz_job.params
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.params
     *
     * @param params the value for quartz_job.params
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setParams(String params) {
        this.params = params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.remark
     *
     * @return the value of quartz_job.remark
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.remark
     *
     * @param remark the value for quartz_job.remark
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quartz_job.create_time
     *
     * @return the value of quartz_job.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quartz_job.create_time
     *
     * @param createTime the value for quartz_job.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_job
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", beanName=").append(beanName);
        sb.append(", cronExpression=").append(cronExpression);
        sb.append(", isPause=").append(isPause);
        sb.append(", jobName=").append(jobName);
        sb.append(", methodName=").append(methodName);
        sb.append(", params=").append(params);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}