package com.example.genator.model;

import java.io.Serializable;

public class RolesMenus implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_menus.menu_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_menus.role_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table roles_menus
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_menus.menu_id
     *
     * @return the value of roles_menus.menu_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_menus.menu_id
     *
     * @param menuId the value for roles_menus.menu_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_menus.role_id
     *
     * @return the value of roles_menus.role_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_menus.role_id
     *
     * @param roleId the value for roles_menus.role_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_menus
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuId=").append(menuId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}