package com.example.genator.model;

import java.io.Serializable;

public class UsersRoles implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_roles.user_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users_roles.role_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users_roles
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_roles.user_id
     *
     * @return the value of users_roles.user_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_roles.user_id
     *
     * @param userId the value for users_roles.user_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users_roles.role_id
     *
     * @return the value of users_roles.role_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users_roles.role_id
     *
     * @param roleId the value for users_roles.role_id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}