package com.example.genator.model;

import java.io.Serializable;
import java.util.Date;

public class Visits implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visits.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visits.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visits.date
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visits.ip_counts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long ipCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visits.pv_counts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private Long pvCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visits.week_day
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private String weekDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table visits
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visits.id
     *
     * @return the value of visits.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visits.id
     *
     * @param id the value for visits.id
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visits.create_time
     *
     * @return the value of visits.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visits.create_time
     *
     * @param createTime the value for visits.create_time
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visits.date
     *
     * @return the value of visits.date
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visits.date
     *
     * @param date the value for visits.date
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visits.ip_counts
     *
     * @return the value of visits.ip_counts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getIpCounts() {
        return ipCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visits.ip_counts
     *
     * @param ipCounts the value for visits.ip_counts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setIpCounts(Long ipCounts) {
        this.ipCounts = ipCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visits.pv_counts
     *
     * @return the value of visits.pv_counts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public Long getPvCounts() {
        return pvCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visits.pv_counts
     *
     * @param pvCounts the value for visits.pv_counts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setPvCounts(Long pvCounts) {
        this.pvCounts = pvCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visits.week_day
     *
     * @return the value of visits.week_day
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public String getWeekDay() {
        return weekDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visits.week_day
     *
     * @param weekDay the value for visits.week_day
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    public void setWeekDay(String weekDay) {
        this.weekDay = weekDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visits
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createTime=").append(createTime);
        sb.append(", date=").append(date);
        sb.append(", ipCounts=").append(ipCounts);
        sb.append(", pvCounts=").append(pvCounts);
        sb.append(", weekDay=").append(weekDay);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}