package com.example.genator.mapper;

import com.example.genator.model.AlipayConfig;
import com.example.genator.model.AlipayConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlipayConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(AlipayConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(AlipayConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(AlipayConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(AlipayConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<AlipayConfig> selectByExampleWithBLOBs(AlipayConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<AlipayConfig> selectByExample(AlipayConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    AlipayConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") AlipayConfig record, @Param("example") AlipayConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") AlipayConfig record, @Param("example") AlipayConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") AlipayConfig record, @Param("example") AlipayConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(AlipayConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(AlipayConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(AlipayConfig record);
}