package com.example.genator.mapper;

import com.example.genator.model.ColumnConfig;
import com.example.genator.model.ColumnConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColumnConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(ColumnConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(ColumnConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(ColumnConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(ColumnConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<ColumnConfig> selectByExample(ColumnConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    ColumnConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") ColumnConfig record, @Param("example") ColumnConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") ColumnConfig record, @Param("example") ColumnConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(ColumnConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(ColumnConfig record);
}