package com.example.genator.mapper;

import com.example.genator.model.DictDetail;
import com.example.genator.model.DictDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(DictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(DictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(DictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(DictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<DictDetail> selectByExample(DictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    DictDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") DictDetail record, @Param("example") DictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") DictDetail record, @Param("example") DictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(DictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_detail
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(DictDetail record);
}