package com.example.genator.mapper;

import com.example.genator.model.GenConfig;
import com.example.genator.model.GenConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GenConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(GenConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(GenConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(GenConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(GenConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<GenConfig> selectByExample(GenConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    GenConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") GenConfig record, @Param("example") GenConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") GenConfig record, @Param("example") GenConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(GenConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_config
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(GenConfig record);
}