package com.example.genator.mapper;

import com.example.genator.model.GenTest;
import com.example.genator.model.GenTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GenTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(GenTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(GenTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(GenTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(GenTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<GenTest> selectByExample(GenTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    GenTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") GenTest record, @Param("example") GenTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") GenTest record, @Param("example") GenTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(GenTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gen_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(GenTest record);
}