package com.example.genator.mapper;

import com.example.genator.model.MenusRoles;
import com.example.genator.model.MenusRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenusRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus_roles
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    long countByExample(MenusRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus_roles
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int deleteByExample(MenusRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus_roles
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int deleteByPrimaryKey(@Param("menuId") Long menuId, @Param("roleId") Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus_roles
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int insert(MenusRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus_roles
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int insertSelective(MenusRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus_roles
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    List<MenusRoles> selectByExample(MenusRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus_roles
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") MenusRoles record, @Param("example") MenusRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus_roles
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByExample(@Param("record") MenusRoles record, @Param("example") MenusRolesExample example);
}