package com.example.genator.mapper;

import com.example.genator.model.MntDatabase;
import com.example.genator.model.MntDatabaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MntDatabaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(MntDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(MntDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(MntDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(MntDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<MntDatabase> selectByExample(MntDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    MntDatabase selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") MntDatabase record, @Param("example") MntDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") MntDatabase record, @Param("example") MntDatabaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(MntDatabase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_database
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(MntDatabase record);
}