package com.example.genator.mapper;

import com.example.genator.model.MntDeployHistory;
import com.example.genator.model.MntDeployHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MntDeployHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_history
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(MntDeployHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_history
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(MntDeployHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_history
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_history
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(MntDeployHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_history
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(MntDeployHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_history
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<MntDeployHistory> selectByExample(MntDeployHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_history
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    MntDeployHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_history
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") MntDeployHistory record, @Param("example") MntDeployHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_history
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") MntDeployHistory record, @Param("example") MntDeployHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_history
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(MntDeployHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_history
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(MntDeployHistory record);
}