package com.example.genator.mapper;

import com.example.genator.model.MntDeployServer;
import com.example.genator.model.MntDeployServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MntDeployServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(MntDeployServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(MntDeployServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(@Param("deployId") Long deployId, @Param("serverId") Long serverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(MntDeployServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(MntDeployServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<MntDeployServer> selectByExample(MntDeployServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") MntDeployServer record, @Param("example") MntDeployServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") MntDeployServer record, @Param("example") MntDeployServerExample example);
}