package com.example.genator.mapper;

import com.example.genator.model.MntDeploy;
import com.example.genator.model.MntDeployExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MntDeployMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(MntDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(MntDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(MntDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(MntDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<MntDeploy> selectByExample(MntDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    MntDeploy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") MntDeploy record, @Param("example") MntDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") MntDeploy record, @Param("example") MntDeployExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(MntDeploy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_deploy
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(MntDeploy record);
}