package com.example.genator.mapper;

import com.example.genator.model.MntServer;
import com.example.genator.model.MntServerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MntServerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(MntServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(MntServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(MntServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(MntServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<MntServer> selectByExample(MntServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    MntServer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") MntServer record, @Param("example") MntServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") MntServer record, @Param("example") MntServerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(MntServer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnt_server
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(MntServer record);
}