package com.example.genator.mapper;

import com.example.genator.model.MyTest;
import com.example.genator.model.MyTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(MyTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(MyTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(MyTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(MyTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<MyTest> selectByExample(MyTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    MyTest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") MyTest record, @Param("example") MyTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") MyTest record, @Param("example") MyTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(MyTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_test
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(MyTest record);
}