package com.example.genator.mapper;

import com.example.genator.model.QiniuConfig;
import com.example.genator.model.QiniuConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QiniuConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    long countByExample(QiniuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int deleteByExample(QiniuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int insert(QiniuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int insertSelective(QiniuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    List<QiniuConfig> selectByExampleWithBLOBs(QiniuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    List<QiniuConfig> selectByExample(QiniuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    QiniuConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") QiniuConfig record, @Param("example") QiniuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") QiniuConfig record, @Param("example") QiniuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByExample(@Param("record") QiniuConfig record, @Param("example") QiniuConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByPrimaryKeySelective(QiniuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(QiniuConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_config
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByPrimaryKey(QiniuConfig record);
}