package com.example.genator.mapper;

import com.example.genator.model.QiniuContent;
import com.example.genator.model.QiniuContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QiniuContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(QiniuContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(QiniuContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(QiniuContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(QiniuContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<QiniuContent> selectByExample(QiniuContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    QiniuContent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") QiniuContent record, @Param("example") QiniuContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") QiniuContent record, @Param("example") QiniuContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(QiniuContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiniu_content
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(QiniuContent record);
}