package com.example.genator.mapper;

import com.example.genator.model.QuartzLog;
import com.example.genator.model.QuartzLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuartzLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(QuartzLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(QuartzLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(QuartzLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(QuartzLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<QuartzLog> selectByExampleWithBLOBs(QuartzLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<QuartzLog> selectByExample(QuartzLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    QuartzLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") QuartzLog record, @Param("example") QuartzLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") QuartzLog record, @Param("example") QuartzLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") QuartzLog record, @Param("example") QuartzLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeySelective(QuartzLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(QuartzLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quartz_log
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByPrimaryKey(QuartzLog record);
}