package com.example.genator.mapper;

import com.example.genator.model.RolesDepts;
import com.example.genator.model.RolesDeptsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolesDeptsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_depts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(RolesDeptsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_depts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(RolesDeptsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_depts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(@Param("roleId") Long roleId, @Param("deptId") Long deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_depts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(RolesDepts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_depts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(RolesDepts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_depts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<RolesDepts> selectByExample(RolesDeptsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_depts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") RolesDepts record, @Param("example") RolesDeptsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_depts
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") RolesDepts record, @Param("example") RolesDeptsExample example);
}