package com.example.genator.mapper;

import com.example.genator.model.RolesMenus;
import com.example.genator.model.RolesMenusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolesMenusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_menus
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    long countByExample(RolesMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_menus
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByExample(RolesMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_menus
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int deleteByPrimaryKey(@Param("menuId") Long menuId, @Param("roleId") Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_menus
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insert(RolesMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_menus
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int insertSelective(RolesMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_menus
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    List<RolesMenus> selectByExample(RolesMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_menus
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") RolesMenus record, @Param("example") RolesMenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_menus
     *
     * @mbg.generated Tue Feb 25 17:45:28 CST 2020
     */
    int updateByExample(@Param("record") RolesMenus record, @Param("example") RolesMenusExample example);
}