package com.example.genator.mapper;

import com.example.genator.model.VerificationCode;
import com.example.genator.model.VerificationCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VerificationCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    long countByExample(VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int deleteByExample(VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int insert(VerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int insertSelective(VerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    List<VerificationCode> selectByExample(VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    VerificationCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") VerificationCode record, @Param("example") VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByExample(@Param("record") VerificationCode record, @Param("example") VerificationCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByPrimaryKeySelective(VerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verification_code
     *
     * @mbg.generated Tue Feb 25 17:45:27 CST 2020
     */
    int updateByPrimaryKey(VerificationCode record);
}